name: Deploy API to Production

on:
  push:
    branches: [ main ]
    paths: 
      - 'server/**'
      - 'shared/**' 
      - 'package*.json'
      - 'infra/docker/api.Dockerfile'
  
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fbpro-mcp/api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript check
        run: npm run check

      - name: Run tests (if available)
        run: npm test || echo "No tests configured"

      - name: Run linting (if available)  
        run: npm run lint || echo "No linting configured"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./infra/docker/api.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}

      - name: Deploy to Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        run: |
          # Install Koyeb CLI
          curl -fsSL https://www.koyeb.com/install.sh | bash
          
          # Deploy to Koyeb service
          koyeb services redeploy fbpro-api \
            --docker-image="${IMAGE_TAG}" \
            --docker-private-registry-secret=ghcr-secret
          
          # Wait for deployment
          echo "Deployment initiated. Check status at https://app.koyeb.com/"
          echo "API will be available at: https://fbpro-api-${GITHUB_REF_NAME}.koyeb.app"

      - name: Deployment notification
        if: always()
        run: |
          echo "::notice title=Deployment Status::API deployed with image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"