name: Nightly Database Backup

on:
  schedule:
    # Run at 3:00 AM UTC daily
    - cron: '0 3 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      retention_days:
        description: 'Backup retention days'
        required: false
        default: '30'
        type: string

env:
  BACKUP_RETENTION_DAYS: ${{ github.event.inputs.retention_days || '30' }}

jobs:
  backup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Install jq for JSON processing
        run: sudo apt-get install -y jq

      - name: Run database backup
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_BACKUP_BUCKET: ${{ secrets.S3_BACKUP_BUCKET }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MONITORING_ENDPOINT: ${{ secrets.MONITORING_ENDPOINT }}
        run: |
          ./ops/scripts/backup.sh

      - name: Upload backup logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backup-logs-${{ github.run_number }}
          path: /tmp/backup-*.log
          retention-days: 7

  notify-on-failure:
    needs: backup
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Notify team of backup failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ -n "$SLACK_WEBHOOK_URL" ]]; then
            curl -X POST -H 'Content-type: application/json' \
              --data "{
                \"text\": \"🚨 CRITICAL: FBPro.MCP nightly backup failed!\",
                \"blocks\": [
                  {
                    \"type\": \"section\",
                    \"text\": {
                      \"type\": \"mrkdwn\",
                      \"text\": \"*🚨 Database Backup Failed*\n\nThe nightly backup for FBPro.MCP has failed. Please investigate immediately.\"
                    }
                  },
                  {
                    \"type\": \"section\",
                    \"fields\": [
                      {
                        \"type\": \"mrkdwn\",
                        \"text\": \"*Workflow:*\n${{ github.workflow }}\"
                      },
                      {
                        \"type\": \"mrkdwn\",
                        \"text\": \"*Run ID:*\n${{ github.run_id }}\"
                      },
                      {
                        \"type\": \"mrkdwn\",
                        \"text\": \"*Time:*\n$(date -u)\"
                      },
                      {
                        \"type\": \"mrkdwn\",
                        \"text\": \"*Branch:*\n${{ github.ref_name }}\"
                      }
                    ]
                  },
                  {
                    \"type\": \"actions\",
                    \"elements\": [
                      {
                        \"type\": \"button\",
                        \"text\": {
                          \"type\": \"plain_text\",
                          \"text\": \"View Logs\"
                        },
                        \"url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
                      }
                    ]
                  }
                ]
              }" \
              "$SLACK_WEBHOOK_URL"
          fi

      - name: Create GitHub issue for backup failure
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Nightly Backup Failed - ${new Date().toISOString().split('T')[0]}`,
              body: `## Database Backup Failure Alert
              
              The nightly database backup has failed. This requires immediate attention to ensure data protection.
              
              **Details:**
              - Workflow: ${context.workflow}
              - Run ID: ${context.runId}
              - Time: ${new Date().toISOString()}
              - Branch: ${context.ref}
              
              **Action Required:**
              1. Check the [workflow logs](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
              2. Verify database connectivity and credentials
              3. Check S3 bucket permissions and availability
              4. Run manual backup if needed
              5. Fix the underlying issue
              
              **Manual Backup Command:**
              \`\`\`bash
              ./ops/scripts/backup.sh
              \`\`\`
              
              cc: @your-team`,
              labels: ['critical', 'backup', 'infrastructure']
            })