# Local development Docker Compose for FBPro.MCP
version: '3.8'

services:
  api:
    build:
      context: ../../
      dockerfile: infra/docker/api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://fbpro:password@postgres:5432/fbpro_dev
      - REDIS_URL=redis://redis:6379
    env_file:
      - ../../.env.local
    depends_on:
      - postgres
      - redis
    volumes:
      - ../../:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fbpro_dev
      - POSTGRES_USER=fbpro
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  # Optional: Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data: